# Generated by Django 5.1.1 on 2024-11-14 05:47

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_tag', models.CharField(max_length=255)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('author_img', models.ImageField(upload_to='media/')),
                ('date_post', models.DateField(auto_now_add=True)),
                ('snippet', models.CharField(default='Click link above to read the blog post', max_length=255)),
                ('author', models.ForeignKey(default='user-name', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(related_name='blog_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('inquiry', models.CharField(default='no quires', max_length=100)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='media/profilepic/')),
                ('website_url', models.CharField(max_length=1300)),
                ('facebook_url', models.CharField(max_length=300)),
                ('instagram_url', models.CharField(max_length=400)),
                ('linkden_url', models.CharField(max_length=130)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
