# Generated by Django 5.1.1 on 2024-11-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapps', '0002_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='linkden_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website_url',
        ),
    ]
