# Generated by Django 5.1.1 on 2024-11-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapps', '0005_rename_userprofile_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='profilephoto',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profilepics/'),
        ),
    ]
