# Generated by Django 5.1.1 on 2024-11-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapps', '0006_remove_profile_profile_pic_profile_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilephoto',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profilepic/'),
        ),
    ]
